name: Docker Build
on:
    push:
      branches:
        main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1

              with:
                username: ${{ secrets.DOCKERUSER }}
                password: ${{ secrets.DOCKERPASS }}

            - name: Build Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERUSER }}/autohetzner:1.0